package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;




/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int adminId;
     private User user;
     private String name;
     private String email;
     private String contactNo;
     private String password;
     private List<Integer> allids=new ArrayList<>();
     private List<Admin> admin=new ArrayList<>();

    public Admin() {
    }

    public Admin(int adminId, User user, String name, String email, String contactNo, String password) {
       this.adminId = adminId;
       this.user = user;
       this.name = name;
       this.email = email;
       this.contactNo = contactNo;
       this.password = password;
    }
   
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public List<Integer> getAllids() {
        return allids;
    }

    public void setAllids(List<Integer> allids) {
        this.allids = allids;
    }

    public List<Admin> getAdmin() {
        return admin;
    }

    public void setAdmin(List<Admin> admin) {
        this.admin = admin;
    }






}


