package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * EmployeeTable generated by hbm2java
 */
public class EmployeeTable  implements java.io.Serializable {


     private String employeeId;
     private String managerId;
     private String departmentId;
     private String departmentName;
     private String postName;
     private String employeeName;
     private String email;
     private String phoneNo;
     private Date hireDate;
     private double salary;
     private Set pharmasists = new HashSet(0);
     private Set doctorTables = new HashSet(0);
     private Set accountants = new HashSet(0);
     private Set nurses = new HashSet(0);
     private Set receptionists = new HashSet(0);
     private List<EmployeeTable> employee=new ArrayList<EmployeeTable>();
     private List<String> allids=new ArrayList<String>();

    public EmployeeTable() {
    }

	
    public EmployeeTable(String employeeId, String managerId, String departmentId, String departmentName, String postName, String employeeName, String email, String phoneNo, Date hireDate, double salary) {
        this.employeeId = employeeId;
        this.managerId = managerId;
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.postName = postName;
        this.employeeName = employeeName;
        this.email = email;
        this.phoneNo = phoneNo;
        this.hireDate = hireDate;
        this.salary = salary;
    }
    public EmployeeTable(String employeeId, String managerId, String departmentId, String departmentName, String postName, String employeeName, String email, String phoneNo, Date hireDate, double salary, Set pharmasists, Set doctorTables, Set accountants, Set nurses, Set receptionists) {
       this.employeeId = employeeId;
       this.managerId = managerId;
       this.departmentId = departmentId;
       this.departmentName = departmentName;
       this.postName = postName;
       this.employeeName = employeeName;
       this.email = email;
       this.phoneNo = phoneNo;
       this.hireDate = hireDate;
       this.salary = salary;
       this.pharmasists = pharmasists;
       this.doctorTables = doctorTables;
       this.accountants = accountants;
       this.nurses = nurses;
       this.receptionists = receptionists;
    }
   
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public String getPostName() {
        return this.postName;
    }
    
    public void setPostName(String postName) {
        this.postName = postName;
    }
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    
    public Set getPharmasists() {
        return this.pharmasists;
    }
    
    public void setPharmasists(Set pharmasists) {
        this.pharmasists = pharmasists;
    }
    public Set getDoctorTables() {
        return this.doctorTables;
    }
    
    public void setDoctorTables(Set doctorTables) {
        this.doctorTables = doctorTables;
    }
    public Set getAccountants() {
        return this.accountants;
    }
    
    public void setAccountants(Set accountants) {
        this.accountants = accountants;
    }
    public Set getNurses() {
        return this.nurses;
    }
    
    public void setNurses(Set nurses) {
        this.nurses = nurses;
    }
    public Set getReceptionists() {
        return this.receptionists;
    }
    
    public void setReceptionists(Set receptionists) {
        this.receptionists = receptionists;
    }

    public List<EmployeeTable> getEmployee() {
        return employee;
    }

    public void setEmployee(List<EmployeeTable> employee) {
        this.employee = employee;
    }

    public List<String> getAllids() {
        return allids;
    }

    public void setAllids(List<String> allids) {
        this.allids = allids;
    }




}


