package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * InpatientTable generated by hbm2java
 */
public class InpatientTable  implements java.io.Serializable {


     private String pid;
     private String roomNo;
     private String labno;
     private Date dateOfAdm;
     private double advance;
     private String admitId;
     private List<InpatientTable> inpatient=new ArrayList<InpatientTable>();
     private List<String> allids=new ArrayList<String>();

    public InpatientTable() {
    }

	
    public InpatientTable(String pid, LabTable labTable, String roomNo, Date dateOfAdm, double advance) {
        this.pid = pid;
        this.roomNo = roomNo;
        this.dateOfAdm = dateOfAdm;
        this.advance = advance;
    }
    public InpatientTable(String pid, LabTable labTable, String roomNo, Date dateOfAdm, double advance, String admitId) {
       this.pid = pid;
       this.roomNo = roomNo;
       this.dateOfAdm = dateOfAdm;
       this.advance = advance;
       this.admitId = admitId;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public Date getDateOfAdm() {
        return this.dateOfAdm;
    }
    
    public void setDateOfAdm(Date dateOfAdm) {
        this.dateOfAdm = dateOfAdm;
    }
    public double getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(double advance) {
        this.advance = advance;
    }
    public String getAdmitId() {
        return this.admitId;
    }
    
    public void setAdmitId(String admitId) {
        this.admitId = admitId;
    }


    public List<String> getAllids() {
        return allids;
    }

    public void setAllids(List<String> allids) {
        this.allids = allids;
    }

    public List<InpatientTable> getInpatient() {
        return inpatient;
    }

    public void setInpatient(List<InpatientTable> inpatient) {
        this.inpatient = inpatient;
    }

    public String getLabno() {
        return labno;
    }

    public void setLabno(String labno) {
        this.labno = labno;
    }




}


