package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Laboratorist generated by hbm2java
 */
public class Laboratorist  implements java.io.Serializable {


     private int id;
     private User user;
     private String name;
     private String email;
     private String contact;
     private String password;
     private Date dod;
     private String gender;
     private List<Integer> allids=new ArrayList<>();
     private List<Laboratorist> laboratorist=new ArrayList<Laboratorist>();

    public Laboratorist() {
    }

	
    public Laboratorist(int id, User user, String name, String email, String contact, String password, Date dod, String gender) {
        this.id = id;
        this.user = user;
        this.name = name;
        this.email = email;
        this.contact = contact;
        this.password = password;
        this.dod = dod;
        this.gender = gender;
    }

   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDod() {
        return this.dod;
    }
    
    public void setDod(Date dod) {
        this.dod = dod;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }



    public List<Integer> getAllids() {
        return allids;
    }

    public void setAllids(List<Integer> allids) {
        this.allids = allids;
    }

    public List<Laboratorist> getLaboratorist() {
        return laboratorist;
    }

    public void setLaboratorist(List<Laboratorist> laboratorist) {
        this.laboratorist = laboratorist;
    }




}


