package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;




/**
 * Nurse generated by hbm2java
 */
public class Nurse  implements java.io.Serializable {


     private String nurseid;
     private Department department;
     private EmployeeTable employeeTable;
     private User user;
     private String nursename;
     private String password;
     private String email;
     private List<String> allids=new ArrayList<>();
     private List<Nurse> nurse=new ArrayList<Nurse>();

    public Nurse() {
    }

	
    public Nurse(String nurseid, Department department, EmployeeTable employeeTable, User user, String nursename, String password, String email) {
        this.nurseid = nurseid;
        this.department = department;
        this.employeeTable = employeeTable;
        this.user = user;
        this.nursename = nursename;
        this.password = password;
        this.email = email;
    }

    public String getNurseid() {
        return this.nurseid;
    }
    
    public void setNurseid(String nurseid) {
        this.nurseid = nurseid;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public EmployeeTable getEmployeeTable() {
        return this.employeeTable;
    }
    
    public void setEmployeeTable(EmployeeTable employeeTable) {
        this.employeeTable = employeeTable;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNursename() {
        return this.nursename;
    }
    
    public void setNursename(String nursename) {
        this.nursename = nursename;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public List<String> getAllids() {
        return allids;
    }

    public void setAllids(List<String> allids) {
        this.allids = allids;
    }

    public List<Nurse> getNurse() {
        return nurse;
    }

    public void setNurse(List<Nurse> nurse) {
        this.nurse = nurse;
    }






}


