package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * OutpatientTable generated by hbm2java
 */
public class OutpatientTable  implements java.io.Serializable {


     private String pid;
     private Date dateOfAdmission;
     private Date dateOfDischarge;
     private String dischargeid;
     private String labno;
     private List<String> allids=new ArrayList<>();
     private List<OutpatientTable> outpatient=new ArrayList<OutpatientTable>();
     

    public OutpatientTable() {
    }

    public OutpatientTable(String pid, LabTable labTable, Date dateOfAdmission, Date dateOfDischarge, String dischargeid) {
       this.pid = pid;
       this.dateOfAdmission = dateOfAdmission;
       this.dateOfDischarge = dateOfDischarge;
       this.dischargeid=dischargeid;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }

    public Date getDateOfAdmission() {
        return this.dateOfAdmission;
    }
    
    public void setDateOfAdmission(Date dateOfAdmission) {
        this.dateOfAdmission = dateOfAdmission;
    }
    public Date getDateOfDischarge() {
        return this.dateOfDischarge;
    }
    
    public void setDateOfDischarge(Date dateOfDischarge) {
        this.dateOfDischarge = dateOfDischarge;
    }

    public String getDischargeid() {
        return dischargeid;
    }

    public void setDischargeid(String dischargeid) {
        this.dischargeid = dischargeid;
    }

    public List<String> getAllids() {
        return allids;
    }

    public void setAllids(List<String> allids) {
        this.allids = allids;
    }

    public List<OutpatientTable> getOutpatient() {
        return outpatient;
    }

    public void setOutpatient(List<OutpatientTable> outpatient) {
        this.outpatient = outpatient;
    }

    public String getLabno() {
        return labno;
    }

    public void setLabno(String labno) {
        this.labno = labno;
    }





}


