package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * PatientTable generated by hbm2java
 */
public class PatientTable  implements java.io.Serializable {


     private String pid;
     private User user;
     private String pname;
     private String psex;
     private int page;
     private String bloodg;
     private double weight;
     private String address;
     private String phoneno;
     private String disease;
     private String doctorid;
     private String password;
     private List<PatientTable> patient=new ArrayList<PatientTable>();
     private List<String> allIds=new ArrayList<String>();

    public PatientTable() {
    }

	
    public PatientTable(String pid, User user, String pname, String psex, int page, double weight, String address, String phoneno, String disease, String doctorid, String password) {
        this.pid = pid;
        this.user = user;
        this.pname = pname;
        this.psex = psex;
        this.page = page;
        this.weight = weight;
        this.address = address;
        this.phoneno = phoneno;
        this.disease = disease;
        this.doctorid = doctorid;
        this.password = password;
    }

   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public String getPsex() {
        return this.psex;
    }
    
    public void setPsex(String psex) {
        this.psex = psex;
    }
    public int getPage() {
        return this.page;
    }
    
    public void setPage(int page) {
        this.page = page;
    }
    public String getBloodg() {
        return this.bloodg;
    }
    
    public void setBloodg(String bloodg) {
        this.bloodg = bloodg;
    }
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
    public String getDisease() {
        return this.disease;
    }
    
    public void setDisease(String disease) {
        this.disease = disease;
    }
    public String getDoctorid() {
        return this.doctorid;
    }
    
    public void setDoctorid(String doctorid) {
        this.doctorid = doctorid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


    public List<PatientTable> getPatient() {
        return patient;
    }

    public void setPatient(List<PatientTable> patient) {
        this.patient = patient;
    }

    public List<String> getAllIds() {
        return allIds;
    }

    public void setAllIds(List<String> allIds) {
        this.allIds = allIds;
    }




}


