package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Receptionist generated by hbm2java
 */
public class Receptionist implements java.io.Serializable {

    private int recId;
    private Department department;
    private EmployeeTable employeeTable;
    private User user;
    private String recName;
    private String gender;
    private Date dob;
    private String recEmail;
    private String recContactno;
    private String recPassword;
    private List<Receptionist> receptionist = new ArrayList<Receptionist>();
    private List<Integer> allIds = new ArrayList<Integer>();

    public Receptionist() {
    }

    public Receptionist(int recId, Department department, EmployeeTable employeeTable, User user, String recName, String gender, Date dob, String recEmail, String recContactno, String recPassword) {
        this.recId = recId;
        this.department = department;
        this.employeeTable = employeeTable;
        this.user = user;
        this.recName = recName;
        this.gender = gender;
        this.dob = dob;
        this.recEmail = recEmail;
        this.recContactno = recContactno;
        this.recPassword = recPassword;
    }

    public int getRecId() {
        return this.recId;
    }

    public void setRecId(int recId) {
        this.recId = recId;
    }

    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public EmployeeTable getEmployeeTable() {
        return this.employeeTable;
    }

    public void setEmployeeTable(EmployeeTable employeeTable) {
        this.employeeTable = employeeTable;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getRecName() {
        return this.recName;
    }

    public void setRecName(String recName) {
        this.recName = recName;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getRecEmail() {
        return this.recEmail;
    }

    public void setRecEmail(String recEmail) {
        this.recEmail = recEmail;
    }

    public String getRecContactno() {
        return this.recContactno;
    }

    public void setRecContactno(String recContactno) {
        this.recContactno = recContactno;
    }

    public String getRecPassword() {
        return this.recPassword;
    }

    public void setRecPassword(String recPassword) {
        this.recPassword = recPassword;
    }


    public List<Integer> getAllIds() {
        return allIds;
    }

    public void setAllIds(List<Integer> allIds) {
        this.allIds = allIds;
    }

    public List<Receptionist> getReceptionist() {
        return receptionist;
    }

    public void setReceptionist(List<Receptionist> receptionist) {
        this.receptionist = receptionist;
    }

}
