package com.pojo;
// Generated Aug 2, 2016 7:42:26 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;




/**
 * RoomTable generated by hbm2java
 */
public class RoomTable  implements java.io.Serializable {


     private String roomNo;
     private String roomType;
     private String status;
     private Double roomCharge;
      private List<RoomTable> roomTable=new ArrayList<RoomTable>();
     private List<String> allIds=new ArrayList<String>();

    public RoomTable() {
    }

	
    public RoomTable(String roomNo, String roomType, String status) {
        this.roomNo = roomNo;
        this.roomType = roomType;
        this.status = status;
    }
    public RoomTable(String roomNo, String roomType, String status, Double roomCharge) {
       this.roomNo = roomNo;
       this.roomType = roomType;
       this.status = status;
       this.roomCharge = roomCharge;
    }
   
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Double getRoomCharge() {
        return this.roomCharge;
    }
    
    public void setRoomCharge(Double roomCharge) {
        this.roomCharge = roomCharge;
    }


    public List<String> getAllIds() {
        return allIds;
    }

    public void setAllIds(List<String> allIds) {
        this.allIds = allIds;
    }

    public List<RoomTable> getRoomTable() {
        return roomTable;
    }

    public void setRoomTable(List<RoomTable> roomTable) {
        this.roomTable = roomTable;
    }




}


